-- The offline half of the baked sound bank (see the note above BAKE_DIR in
-- engine/audio). Renders every cue and every variant through the ordinary queue
-- and writes each one out as a 16-bit WAV, plus the manifest the game loads.
--
-- It does not encode anything: tools/bake_audio.sh runs this, hands the WAVs to
-- oggenc and drops the result into src/bake/audio. Running it by hand:
--   BOTS_BAKE_OUT=/tmp/bake BOTS_SCENE=tools.bakescene tools/shot.sh 1 1 /tmp/x
--
-- Nothing here may depend on the machine it runs on. The manifest carries no
-- timestamp and no path, so two bakes of the same tree are the same bytes and a
-- rebuild-and-diff is a real check.

-- love.load has already registered the bank through the module the game holds,
-- and Audio.renderAll insists on a bank nothing has touched. Take a private copy
-- of the module rather than reaching into the game's one.
package.loaded["src.engine.audio"] = nil
package.loaded["src.engine.synth"] = nil
local Audio = require("src.engine.audio")

local S = {}
local floor = math.floor

local function le(v, n)
  local t = {}
  for i = 1, n do t[i] = string.char(v % 256) v = floor(v / 256) end
  return table.concat(t)
end

--- One buffer as a canonical 16-bit PCM WAV. Buf:toPCM already clamps and
--- rounds exactly the way Buf:toSoundData does, so the file and the SoundData
--- the game would have built from the same buffer hold identical samples.
local function wav(path, buf)
  local pcm = buf:toPCM()
  local byteRate = buf.rate * buf.ch * 2
  local header = "RIFF" .. le(36 + #pcm, 4) .. "WAVEfmt " .. le(16, 4) .. le(1, 2) ..
                 le(buf.ch, 2) .. le(buf.rate, 4) .. le(byteRate, 4) ..
                 le(buf.ch * 2, 2) .. le(16, 2) .. "data" .. le(#pcm, 4)
  local f = io.open(path, "wb")
  if not f then error("bake: cannot write " .. path, 0) end
  f:write(header) f:write(pcm) f:close()
  return #pcm + 44
end

--- The meter envelope, verbatim from the buffer it was measured on. It is four
--- decimal places of an RMS value that drives a 40-pixel bar, and recomputing it
--- at load would mean walking six million samples in Lua -- which is most of
--- what the bake exists to avoid.
local function envLiteral(env)
  local t = { "{ hz = ", tostring(env.hz), ", n = ", tostring(env.n) }
  for i = 1, env.n do
    t[#t + 1] = ", "
    t[#t + 1] = string.format("%.4f", env[i] or 0)
  end
  t[#t + 1] = " }"
  return table.concat(t)
end

function S:enter()
  local out = os.getenv("BOTS_BAKE_OUT") or "/tmp/bots_bake"
  local order, cues = {}, {}
  local wavBytes, count = 0, 0
  local t0 = love.timer.getTime()

  Audio.renderAll(function(name, slot, buf, loop, env)
    local cue = cues[name]
    if not cue then
      cue = { loop = loop, recs = {} }
      cues[name] = cue
      order[#order + 1] = name
    end
    local file = string.format("%s_%d", name, slot)
    wavBytes = wavBytes + wav(out .. "/" .. file .. ".wav", buf)
    count = count + 1
    cue.recs[slot] = {
      f = file .. ".ogg", n = buf.n, ch = buf.ch, dur = buf.n / buf.rate,
      env = envLiteral(env),
    }
  end)

  local t1 = love.timer.getTime()
  table.sort(order)

  local m = {
    "-- Generated by tools/bake_audio.sh. Do not edit; re-bake.",
    "-- The sound bank, rendered offline once instead of by every browser tab.",
    "-- `fingerprint` is md5(synth.lua .. audio.lua): if it does not match at",
    "-- load, the specs moved without the bake and engine/audio says so and",
    "-- synthesizes instead of shipping the wrong sound.",
    "return {",
    "  version = 2,",
    "  rate = " .. tostring(Audio.rate) .. ",",
    "  fingerprint = " .. string.format("%q", Audio.bakeFingerprint()) .. ",",
    "  cues = {",
  }
  for _, name in ipairs(order) do
    local cue = cues[name]
    m[#m + 1] = string.format("    %s = { loop = %s,", name, tostring(cue.loop))
    for i = 1, #cue.recs do
      local r = cue.recs[i]
      m[#m + 1] = string.format("      { f = %q, n = %d, ch = %d, dur = %.6f, env = %s },",
                                r.f, r.n, r.ch, r.dur, r.env)
    end
    m[#m + 1] = "    },"
  end
  m[#m + 1] = "  },"
  m[#m + 1] = "}"

  local f = io.open(out .. "/manifest.lua", "wb")
  if not f then error("bake: cannot write the manifest into " .. out, 0) end
  f:write(table.concat(m, "\n")) f:write("\n") f:close()

  print(string.format("BAKE %d variants, %d cues, %.2f MB of WAV, %.2f s of DSP",
                      count, #order, wavBytes / 1048576, t1 - t0))
  if love.event then love.event.quit() end
end

function S:draw() end
return S
